name: Windows RDP Environment

on:
  workflow_dispatch:
    inputs:
      crd_code:
        description: 'Kode Otorisasi dari Chrome Remote Desktop'
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download & Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest -Uri https://dl.google.com/remotedesktop/chromeremotedesktophost.msi -OutFile chromeremotedesktophost.msi
          Start-Process msiexec.exe -Wait -ArgumentList '/i chromeremotedesktophost.msi /quiet'

      - name: Setup Chrome Remote Desktop
        run: |
          ${{ github.event.inputs.crd_code }} -pin=123456

      - name: Keep Alive
        run: |
          $loop = $true
          while($loop) {
            Start-Sleep -Seconds 300
          }
